### ISSUE TITLE
Blank "view" URL in resource grid

### ISSUE THREAD

**Issue by pchevali** [GeoNodeUserGroup-DE/contrib_externalapplications#8] opened 2024-06-26 10:58 UTC
Hi, 

I have been testing this contrib app but and I was not able to have the "View" link to follow the detail url.
I only tested with the latest version of geonode (4.3). It seems to me that this part is not working unless by specifying a "subtype" for the external application (I used document and it works).

This seems related to the following lines in geonode mapstore client ( but it hasn't changed since a while ):

https://github.com/GeoNode/geonode-mapstore-client/blob/master/geonode_mapstore_client/client/js/components/ResourceCard/ResourceCard.jsx#L44-L49

Am I missing something here ?

Regards

**Comment by ridoo** [comment] 2024-06-27 08:34
@pchevali yes .. the problem is, that ATM there is no way to customize UI behaviour at this level of detail via contrib module. This is missing from the documentation, I guess. It is just a one-liner:

https://github.com/Thuenen-GeoNode-Development/geonode-mapstore-client/blob/112b26b45ac8fe85a129625c160a7998a531f8cf/geonode_mapstore_client/client/js/components/DetailsPanel/DetailsPanel.jsx#L157

There is a discussion [focussing on dev experience](https://github.com/GeoNode/geonode-mapstore-client/issues/1546) when customizing geonode-mapstore-client which is IMHO expandable.

**Comment by pchevali** [comment] 2024-06-27 09:06
Ok I understand. So this must be the point where we need to fork the client.
Indeed there are other changes related to externalapplications : https://github.com/search?q=repo%3AThuenen-GeoNode-Development%2Fgeonode-mapstore-client%20externalapplication&type=code

**Comment by ridoo** [comment] 2024-07-01 06:19
@pchevali I will close this issue here for now.

**Closed by ridoo** 2024-07-01 06:19 UTC
